#Configuration for CompassNavigation by Adzwoolly and xMRKIRO!
#Each number represents the slot in the Compass GUI.
#If the slot is not in use, set Enabled to False!
#Item is the item to represent the teleport in the Compass GUI.
#USE THE WORDS FROM THE LINK FOR ITEMS!
#http://jd.bukkit.org/dev/doxygen/d6/d0e/enumorg_1_1bukkit_1_1Material.html
#It's caps sensitive, so be careful!
#Please use a whole number (not decimal) for Yaw and Pitch
#Pitch: -90 = Sky, +90 = Floor
#Name Can have colour codes.  The colourcode is '§' e.g.  '§6' for gold
#Use "§" for colours in descriptions. "null" will make no description.
#Up to 6 rows are supported

Item: COMPASS
GUIName: CompassNavigation
Rows: 1
1:
  Enabled: true
  Item: FIRE
  Name: To §6fire land!
  Desc: To the land of fire!
  World: world
  X: 70
  Y: 76
  Z: 66
  Yaw: 0
  Pitch: 90
2:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
3:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
4:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
5:
  Enabled: true
  Item: MOB_SPAWNER
  Name: §8 To the caves of ~4Darkness
  Desc: null
  World: world
  X: 63
  Y: 14
  Z: -12
  Yaw: 0
  Pitch: 0
6:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
7:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
8:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
9:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
10:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
11:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
12:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
13:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 
14:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
15:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
16:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
17:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
18:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
19:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
20:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
21:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
22:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 
23:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
24:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
25:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
26:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
27:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
28:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
29:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
30:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
31:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
32:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
33:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
34:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
35:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
36:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
37:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
38:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
39:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
40:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
41:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
42:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
43:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
44:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
45:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
46:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
47:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
48:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
49:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
50:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
51:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
52:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
53:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
54:
  Enabled: false
  Item: GRASS
  Name: Default
  Desc: null
  World: world
  X: 0
  Y: 60
  Z: 0
  Yaw: 0
  Pitch: 0
DisabledWorlds:
  - myworld
  - potatoworld
