# Configuration for CompassNavigation by Adzwoolly and xMRKIRO!
# Each number represents the slot in the compass GUI.
# If the slot is not in use, set Enabled to False!
# Item is the item to represent the teleport in the Compass GUI.
# USE THE WORDS FROM THE LINK FOR ITEMS!
# http://jd.bukkit.org/dev/doxygen/d6/d0e/enumorg_1_1bukkit_1_1Material.html
# It's caps sensitive, so be careful!
# Please use a whole number (not decimal) for Yaw and Pitch
# Pitch: -90 = Sky, +90 = Floor
# The name can have colour codes.  The colourcode is '&', e.g. '&6' for gold
# Use "ยง" for colours in descriptions, aka lores. "null" won't create a lore.
# Up to 6 rows are supported.
# Don't forget to add items to the config!

Item: COMPASS
GUIName: CompassNavigation
Rows: 1
1:
  Enabled: true
  Item: FIRE
  Name: To &6fire land!
  Desc: To the land of fire!
  World: world
  X: 70
  Y: 76
  Z: 66
  Yaw: 0
  Pitch: 90
DisabledWorlds:
  - myworld
  - potatoworld
