# Configuration for CompassNavigation by Adzwoolly and xMRKIRO!
# Each number represents the slot in the compass GUI.
# If the slot is not in use, set Enabled to False!
# Item is the item to represent the teleport in the Compass GUI.
# Use item IDs for specifying an item!
# http://www.minecraftwiki.net/wiki/Data_values#Item_IDs
# Please use a whole number (not decimal) for Yaw and Pitch
# Pitch: -90 = Sky, +90 = Floor
# The name and lore can have colour codes.  The colourcode is '&', e.g. '&6' for gold
# Up to 6 rows are supported.
# Don't forget to add items to the config!

Item: 345
GUIName: CompassNavigation
Rows: 1
1:
  Enabled: true
  Item: 51
  Name: To &6fire land!
  Desc: To the land of fire!
  World: world
  X: 70
  Y: 76
  Z: 66
  Yaw: 0
  Pitch: 90
DisabledWorlds:
  - myworld
  - potatoworld
